### ISSUE TITLE
wallet always showing 0 balance

### ISSUE THREAD

**Issue by zebpaypeswani** [lky1001/tron-android-wallet#20]
Hi I set up a test node on aws and it's running fine. 

I changed the arrays.xml file in android app pointing to my node

   `<array name="fullnode.ip.list">
        <item>xx:xxx:xx:xxx:50051</item>
    </array>`

    `<array name="solidity.ip.list">
        <item>xx:xxx:xx:xxx:50051</item>
    </array>`
It's connected to the node. Now I create a Wallet which give me private/pub key. I login in test.tronscan.org using private key and request for test tokens. They provided 10,000 TRX for testing.
Now when I see the balance in Android app the balance is always 0. Also it generate address start with 27 `27h46fgf6C1NwjzRjg5ykEVAKHBhpwH1M8u` but the address which tronscan show start with T `TTwo8NLijsMi3pBWMELUAaJaVGEDRo3fvM` can you please tell me where is the issue?

**Comment by lky1001** [comment]
Hi @zebpaypeswani 
27h46fgf6C1NwjzRjg5ykEVAKHBhpwH1M8u is tron test address(start with 2)
And TTwo8NLijsMi3pBWMELUAaJaVGEDRo3fvM(start with T) is mainnet address.

You can change address format via Android Build Variant.
devDebug or devRelease is test address, mainDebug or mainRelease is mainnet address.

Check org.tron.core.config.Paramter interface.

Thanks.

**Comment by zebpaypeswani** [comment]
@lky1001 thanks for a real quick response. I run the Android app as devDebug. when I created the private/pub key using android app and go to [TronScan](https://test.tronscan.org/) click on wallet and sign in using private key. where I request for test tokens. The question is why balance is not updating in Android app. I even run using mainDebug and address is correct as mainnet but still balance is 0
I can check [here the balance](https://test.tronscan.org/#/address/TTwo8NLijsMi3pBWMELUAaJaVGEDRo3fvM)   it's showing 10,000 TRX

**Comment by lky1001** [comment]
@zebpaypeswani 
hm... 
I think that your node not sync tron testnet.
Try changing fullnode ip to 52.11.100.58(tron testnet node, https://test.tronscan.org/#/nodes)

**Comment by zebpaypeswani** [comment]
@lky1001 I tried with another nodes still 0 balance. I don't know where I am mistaking.

**Comment by lky1001** [comment]
@zebpaypeswani 
hm.. ok. 
I will check tomorrow.
Time to sleep in korean.
Thanks.

**Comment by lky1001** [comment]
@zebpaypeswani 
Sorry, my mistake.
Some data get from tronscan api.

Check here https://github.com/lky1001/tron-android-wallet/blob/develop/tronlib/src/main/java/com/devband/tronlib/Hosts.java

I can't not found api from test.tronscan.org.

maybe test.tronscan.org does not support api.

**Comment by zebpaypeswani** [comment]
Copy Pasted here...

when I generate address from wallet-cli or android app for testnet config the address start with `27`. when I create test account in test.tronscan.org the address start with `T` . I got to know that address start with 27 is testnet address and which start with `T` is main net address. My question is why [tronscan](https://test.tronscan.org) generating main net address even though I am opening test account..
Also how can I transfer TRX between these addresses. because tronscan does not recognize address which start with `27`

**Comment by zebpaypeswani** [comment]
@lky1001 sorry to bother I resolved the issue at least in wallet-cli the type need to be mainnet even your full node is testnet.

**Comment by kookiekrak** [comment]
Hi, testnet addresses with 27 are deprecated.

All current testnet addresses match mainnet. Please update this if possible!

**Comment by lky1001** [comment]
@kookiekrak thanks. I will update soon.

**Comment by lky1001** [comment]
@zebpaypeswani 
balance get from api.tronscan.org.
not from tron node grpc.

If you want to get balance from tron node
check this code.

https://github.com/lky1001/tron-android-wallet/commit/281b3f1f3f4e4f06d7de7171794a395552a620ba

**Comment by zebpaypeswani** [comment]
There is test api https://testapi.tronscan.org

**Comment by lky1001** [comment]
@zebpaypeswani Good. Everything ok?
